name: Build with Gradle

on:
  - workflow_dispatch
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: 8.0.202+8
        distribution: 'adopt'
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew clean build --info -Partifactory_build_url=$ARTIFACTORY_BUILD_URL
