name: Sonarqube
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  jaCoCo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build and generate Sonarqube report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: cb-lukasz_cb-hp-service-sonar-integration-test
          SONAR_PROJECT_NAME: cb-hp-service-sonar-integration-test
        run: |
          chmod +x gradlew
          ./gradlew build integrationTest sonarqube -x test --info